# Generated by Django 5.1 on 2024-08-20 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
        ('churchprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='advancedusersphotos')),
                ('userid', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('levelofeducation', models.CharField(blank=True, max_length=255, null=True)),
                ('salesskills', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('curriculumvitae', models.FileField(blank=True, max_length=255, null=True, upload_to='advanceduserscv')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('module_profile', models.BooleanField(default=True)),
                ('module_sales', models.BooleanField(default=False)),
                ('module_documentation', models.BooleanField(default=True)),
                ('module_admin', models.BooleanField(default=False)),
                ('module_church', models.BooleanField(default=False)),
                ('module_chat', models.BooleanField(default=False)),
                ('module_system', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advuserprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiumamount', models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True)),
                ('packagetype', models.CharField(blank=True, max_length=255, null=True)),
                ('commissionrate', models.CharField(blank=True, max_length=255, null=True)),
                ('commissionamount', models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True)),
                ('commissionagentid', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_church', to='churchprofile.churchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SalesUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('activestatus', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesusracc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('received', models.BooleanField(blank=True, default=False)),
                ('read', models.BooleanField(blank=True, default=False)),
                ('resolved', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('chatuser', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechChatTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('received', models.BooleanField(blank=True, default=False)),
                ('read', models.BooleanField(blank=True, default=False)),
                ('resolved', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatticket_branch', to='branches.branches')),
                ('chatadmin', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatticketadmin', to=settings.AUTH_USER_MODEL)),
                ('chatuser', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatticketuser', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techchatticket_church', to='churchprofile.churchprofile')),
            ],
        ),
    ]
