# Generated by Django 5.1 on 2024-08-20 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
        ('churchprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicetype', models.CharField(blank=True, choices=[('Church Group', 'Church Group'), ('Ministerial Position', 'Ministerial Position')], default=None, max_length=50, null=True)),
                ('choice', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_church', to='churchprofile.churchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churchgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churchgroups_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churchgroups_church', to='churchprofile.churchprofile')),
            ],
        ),
    ]
