# Generated by Django 4.0 on 2024-09-04 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicetype', models.CharField(blank=True, choices=[('Church Group', 'Church Group'), ('Ministerial Position', 'Ministerial Position')], default=None, max_length=50, null=True)),
                ('choice', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churchgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
