# Generated by Django 4.0 on 2024-09-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('administration', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchgroup',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churchgroups_branch', to='branches.branches'),
        ),
        migrations.AddField(
            model_name='churchgroup',
            name='church',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churchgroups_church', to='accounts.church'),
        ),
        migrations.AddField(
            model_name='choices',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_branch', to='branches.branches'),
        ),
        migrations.AddField(
            model_name='choices',
            name='church',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_church', to='accounts.church'),
        ),
    ]
