# Generated by Django 5.1 on 2024-08-20 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
        ('churchprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('quantity', models.CharField(default='', max_length=255, null=True)),
                ('amount', models.CharField(default=None, max_length=255)),
                ('approvedby', models.CharField(default='', max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accexpenditure_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accexpenditure_church', to='churchprofile.churchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('payerfullname', models.CharField(max_length=255)),
                ('accountname', models.CharField(default='', max_length=255)),
                ('accounttype', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(default='', max_length=255)),
                ('payinby', models.CharField(default='', max_length=255, null=True, verbose_name='Payin By')),
                ('paymentmethod', models.CharField(default='', max_length=255)),
                ('cheq_chequenumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cheq_micrcode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cheq_accountnumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('wirtrans_accountnumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instantpledge', models.BooleanField(blank=True, default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accpayment_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accpayment_church', to='churchprofile.churchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('accounttype', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('purpose', models.TextField(blank=True, default='', null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountsetup_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountsetup_church', to='churchprofile.churchprofile')),
            ],
        ),
    ]
