# Generated by Django 5.1 on 2024-08-20 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
        ('churchprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('nowithcountrycode', models.IntegerField(blank=True, null=True)),
                ('nowithoutcountrycode', models.IntegerField(blank=True, null=True)),
                ('supportednetworks', models.CharField(blank=True, max_length=200, null=True)),
                ('nonetstartwith', models.IntegerField(blank=True, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('accordingto', models.CharField(blank=True, max_length=255, null=True)),
                ('fromaddr', models.CharField(blank=True, max_length=255, null=True)),
                ('toaddr', models.TextField(blank=True, max_length=255, null=True)),
                ('sentstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailsent_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailsent_church', to='churchprofile.churchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NotifierSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sender', models.CharField(default='ChAffairs', max_length=11)),
                ('sms_verification', models.BooleanField(blank=True, default=False)),
                ('sms_verification_status', models.CharField(blank=True, default='Unverified', max_length=100, null=True)),
                ('phone_countrycode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email_from', models.EmailField(default='branch@churchaffairs.com', max_length=255)),
                ('notifierpoints', models.BigIntegerField(blank=True, default=0, null=True)),
                ('rnotif_memberadd', models.BooleanField(blank=True, default=True)),
                ('rnotif_guestadd', models.BooleanField(blank=True, default=True)),
                ('rnotif_financeadd', models.BooleanField(blank=True, default=True)),
                ('lastmodified', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifier_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifier_church', to='churchprofile.churchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PushSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(blank=True, max_length=255, null=True)),
                ('mediafile', models.FileField(blank=True, null=True, upload_to='chaffairsmedia/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('accordingto', models.CharField(blank=True, max_length=255, null=True)),
                ('sentstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pushnotif_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pushnotif_church', to='churchprofile.churchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SmsSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderid', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('accordingto', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumbers', models.TextField(blank=True, max_length=255, null=True)),
                ('sentstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smssent_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smssent_church', to='churchprofile.churchprofile')),
            ],
        ),
    ]
