# Generated by Django 4.0 on 2024-09-04 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('motto', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('owner_fullname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('owner_phone', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=100)),
                ('owner_username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('confirm_password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('postal', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_plan', models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], default='Basic', max_length=255, null=True)),
                ('next_expiry_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.URLField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_church', to='accounts.church')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='auth.user')),
            ],
        ),
    ]
