# Generated by Django 4.0 on 2024-09-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='owner_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='owner_fullname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='owner_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='owner_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='church',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='church',
            name='owner_phone',
        ),
        migrations.AlterField(
            model_name='church',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
