# Generated by Django 4.0 on 2024-09-05 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='nextchargedate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 5, 20, 26, 59, 49549), null=True),
        ),
    ]
