# Generated by Django 5.1 on 2024-08-24 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='nextchargedate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 24, 8, 37, 24, 603626), null=True),
        ),
    ]
