# Generated by Django 4.0 on 2024-09-05 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='nextchargedate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 6, 6, 46, 37, 208933), null=True),
        ),
    ]
