# Generated by Django 4.0 on 2024-09-16 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branches_nextchargedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='nextchargedate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 17, 3, 20, 47, 960803), null=True),
        ),
    ]
