# Generated by Django 4.0 on 2024-10-08 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_alter_branches_nextchargedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='nextchargedate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 7, 19, 47, 5, 263326), null=True),
        ),
    ]
