# Generated by Django 4.0 on 2024-10-22 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branches_nextchargedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='nextchargedate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 21, 19, 11, 58, 483780), null=True),
        ),
    ]
