# Generated by Django 5.1 on 2024-08-20 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
        ('churchprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fulltext', models.TextField(blank=True, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchreport_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchreport_church', to='churchprofile.churchprofile')),
            ],
        ),
    ]
