# Generated by Django 4.0 on 2024-09-04 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestid', models.CharField(blank=True, max_length=100, null=True)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='guestphotos')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], default=None, max_length=100, null=True, verbose_name='Title')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default=None, max_length=100, null=True, verbose_name='Gender')),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('placeofbirth', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('homeaddress', models.TextField(blank=True, null=True)),
                ('postaladdress', models.TextField(blank=True, null=True)),
                ('phonenumber1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone1_rnotif', models.BooleanField(blank=True, default=True)),
                ('phonenumber2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone2_rnotif', models.BooleanField(blank=True, default=False)),
                ('emailaddress1', models.EmailField(blank=True, max_length=100, null=True)),
                ('email1_rnotif', models.BooleanField(blank=True, default=True)),
                ('emailaddress2', models.EmailField(blank=True, max_length=100, null=True)),
                ('email2_rnotif', models.BooleanField(blank=True, default=False)),
                ('invitedby', models.CharField(blank=True, max_length=100, null=True)),
                ('purposeofvisit', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_church', to='accounts.church')),
            ],
        ),
    ]
