# Generated by Django 5.1 on 2024-08-20 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('subscriptionstatus', models.BooleanField(blank=True, default=False, max_length=255)),
                ('code', models.CharField(max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('featureshortname', models.CharField(blank=True, max_length=100, null=True)),
                ('featurelongname', models.CharField(blank=True, max_length=255, null=True)),
                ('featureicon', models.ImageField(blank=True, max_length=255, null=True, upload_to='featuresmedia')),
                ('featureshortdescription', models.TextField(blank=True, null=True)),
                ('featurelongdescription', models.TextField(blank=True, null=True)),
                ('ordernumber', models.CharField(blank=True, max_length=100, null=True)),
                ('featurecolor', models.CharField(blank=True, max_length=100, null=True)),
                ('activestatus', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('subinfo', models.CharField(blank=True, max_length=255, null=True)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('photograph', models.ImageField(blank=True, max_length=255, null=True, upload_to='testimoniesmedia')),
                ('activestatus', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
