# Generated by Django 4.0 on 2024-09-04 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churchname', models.CharField(blank=True, max_length=255, null=True)),
                ('registererfullname', models.CharField(blank=True, max_length=255, null=True)),
                ('registereremail', models.EmailField(blank=True, max_length=255, null=True)),
                ('registerertelephonecode', models.CharField(blank=True, max_length=255, null=True)),
                ('registerertelephone', models.CharField(blank=True, max_length=255, null=True)),
                ('paymentplan', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('expired_date', models.BigIntegerField(blank=True, default=0, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('churchname', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('residentialaddress', models.TextField(blank=True, null=True)),
                ('postaladdress', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='churchlogos')),
                ('motto', models.TextField(blank=True, max_length=255, null=True)),
                ('colours', models.CharField(blank=True, max_length=100, null=True)),
                ('registererfullname', models.CharField(blank=True, max_length=255, null=True)),
                ('registereremail', models.EmailField(blank=True, max_length=255, null=True)),
                ('registerertelephonecode', models.CharField(blank=True, max_length=255, null=True)),
                ('registerertelephone', models.CharField(blank=True, max_length=255, null=True)),
                ('registererusername', models.CharField(blank=True, max_length=255, null=True)),
                ('registererpassword', models.CharField(blank=True, max_length=255, null=True)),
                ('securityquestion', models.CharField(blank=True, max_length=255, null=True)),
                ('securityanswer', models.CharField(blank=True, max_length=255, null=True)),
                ('totalnotifierpoints', models.IntegerField(blank=True, default=0, null=True)),
                ('assignednotifierpoints', models.IntegerField(blank=True, default=0, null=True)),
                ('freenotifierpoints', models.IntegerField(blank=True, default=0, null=True)),
                ('module_dashboard', models.BooleanField(default=True)),
                ('module_branches', models.BooleanField(default=True)),
                ('module_branchusers', models.BooleanField(default=True)),
                ('module_members', models.BooleanField(default=True)),
                ('module_members_add', models.BooleanField(default=True)),
                ('module_members_update', models.BooleanField(default=True)),
                ('module_members_delete', models.BooleanField(default=True)),
                ('module_guests', models.BooleanField(default=True)),
                ('module_guests_add', models.BooleanField(default=True)),
                ('module_guests_update', models.BooleanField(default=True)),
                ('module_guests_delete', models.BooleanField(default=True)),
                ('module_attendance', models.BooleanField(default=True)),
                ('module_notifier', models.BooleanField(default=True)),
                ('module_notifier_sms', models.BooleanField(default=True)),
                ('module_notifier_emails', models.BooleanField(default=True)),
                ('module_notifier_mobileapp', models.BooleanField(default=True)),
                ('module_notifier_settings', models.BooleanField(default=True)),
                ('module_finance', models.BooleanField(default=True)),
                ('module_finance_individualincome', models.BooleanField(default=True)),
                ('module_finance_bulkincome', models.BooleanField(default=True)),
                ('module_finance_expenditure', models.BooleanField(blank=True, default=True)),
                ('module_finance_trialbalance', models.BooleanField(default=True)),
                ('module_finance_balancesheet', models.BooleanField(default=True)),
                ('module_finance_finalaccounts', models.BooleanField(default=True)),
                ('module_finance_accountsetup', models.BooleanField(default=True)),
                ('module_branchreport', models.BooleanField(default=True)),
                ('module_grandreport', models.BooleanField(default=True)),
                ('module_support', models.BooleanField(default=True)),
                ('module_administration', models.BooleanField(default=True)),
                ('module_administration_payment', models.BooleanField(default=True)),
                ('module_administration_profile', models.BooleanField(default=True)),
                ('module_administration_branchprofile', models.BooleanField(default=True)),
                ('module_administration_branchusers', models.BooleanField(default=True)),
                ('module_administration_choices', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churchprofile', to='auth.user')),
            ],
        ),
    ]
