# Generated by Django 5.1 on 2024-08-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_members_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='dob',
            new_name='datebaptised',
        ),
        migrations.AddField(
            model_name='member',
            name='activestatus',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='churchgroups',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='convert',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='datebornagain',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='deviceid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email1_rnotif',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email2_rnotif',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='emailaddress1',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='emailaddress2',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='homeaddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='memberid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='ministerialposition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone1_rnotif',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone2_rnotif',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='phonenumber1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phonenumber2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='postaladdress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pushdeviceid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pushdeviceid_rnotif',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
