# Generated by Django 5.1 on 2024-08-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
        ('churchprofile', '0001_initial'),
        ('members', '0003_rename_dob_member_datebaptised_member_activestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_branch', to='branches.branches'),
        ),
        migrations.AddField(
            model_name='member',
            name='church',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_church', to='churchprofile.churchprofile'),
        ),
    ]
