# Generated by Django 4.0 on 2024-09-04 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendancetype', models.CharField(blank=True, default='Church Attendance', max_length=255, null=True)),
                ('attendantid', models.CharField(blank=True, max_length=100, null=True)),
                ('programid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('attendance', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programid', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('attendancetype', models.CharField(blank=True, default='Church Attendance', max_length=255, null=True)),
                ('male', models.BigIntegerField(blank=True, default=0, null=True)),
                ('female', models.BigIntegerField(blank=True, default=0, null=True)),
                ('children', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
