# Generated by Django 5.1 on 2024-08-20 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branches_nextchargedate'),
        ('churchprofile', '0001_initial'),
        ('members', '0003_rename_dob_member_datebaptised_member_activestatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendancetype', models.CharField(blank=True, default='Church Attendance', max_length=255, null=True)),
                ('attendantid', models.CharField(blank=True, max_length=100, null=True)),
                ('programid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('attendance', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_church', to='churchprofile.churchprofile')),
                ('membername', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_member', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programid', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('attendancetype', models.CharField(blank=True, default='Church Attendance', max_length=255, null=True)),
                ('male', models.BigIntegerField(blank=True, default=0, null=True)),
                ('female', models.BigIntegerField(blank=True, default=0, null=True)),
                ('children', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendanceprogram_branch', to='branches.branches')),
                ('church', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendanceprogram_church', to='churchprofile.churchprofile')),
            ],
        ),
    ]
