# Generated by Django 4.0 on 2024-09-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('accounts', '0001_initial'),
        ('members', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceprogram',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendanceprogram_branch', to='branches.branches'),
        ),
        migrations.AddField(
            model_name='attendanceprogram',
            name='church',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendanceprogram_church', to='accounts.church'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_branch', to='branches.branches'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='church',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_church', to='accounts.church'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='membername',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_member', to='members.member'),
        ),
    ]
